### PR TITLE
Add append_metadata to gulltracking package

### PR DESCRIPTION
**Pull request by damianooldoni**
This PR adds a function called `append_metadata()` to the package. I implemented it as discussed in #23. 

I have written
1. function
2. documentation
3. tests

In order to accomplish 2 (examples) and 3 I included two small datasets in the package as described in https://r-pkgs.org/data.html#data

@peterdesmet: name of the function can be surely improved.

### CODE REVIEW

**Comment by peterdesmet** [comment]
The R object `lbbg_reference` contains only herring gulls: the join works, but all appended data is empty. Best to update the object to contain ref data for Lesser black-backed gulls. 😄

**Review by peterdesmet — CHANGES_REQUESTED** [review]
- I have updated function description
- I have updated data.R and rebuild the objects

Want should change:

- gps and reference_data can contain more shared columns that those used in join. The shared columns in reference_data should be dropped with a warning (currently no columns are added)
- I think we might want to use `ref_data` instead of `reference_data`: it types faster and is as clear.

**Comment by damianooldoni** [comment]
I think I did everything requested. Test added as well. Documentation too about the dropping and warning. @peterdesmet : a last check before merging? Thanks.

**Comment by peterdesmet** [comment]
You use `usethis::use_data()` to save the data. Should the example be updated to reflect that?

**Review by peterdesmet — CHANGES_REQUESTED** [review]
Tested. 3 remaining questions:

1. Should we use `save()` or `usethis::use_data()` in the data examples?
2. Should we really have a default for `ref_cols` (renamed from `reference_cols`): it is a bit counter intuitive and makes it harder to add all columns imo
3. The same columns in both files doesn't really work for me:

```R
> lbbg_ref_data <- lbbg_ref_data %>% rename("study-name" = "study-site")
> test <- append_metadata(lbbg_gps, lbbg_ref_data)
Warning message:
Unknown columns: `study-name` 
```

**Comment by damianooldoni** [comment]
1. I used `usethis` just because I couldn't install the package after pulling your commits. No idea why. I made the rda files via `usethis` again and it worked. Still, I would not change it. 

2. This is something I think Jan's opinion can be useful. I understand perfectly your point by the way. My opnion is: use all columns of `ref_data` as default. Something like `append_metadata(gps, ref_data, ref_cols = NULL)` where if not NULL then it is a vector of column names of `ref_data`

3. Solved via aee7883

**Comment by peterdesmet** [comment]
I'm still getting the `unknown columns` warning:

```R
lbbg_ref_data_2 <- lbbg_ref_data %>% rename("study-name" = "study-site")
test <- append_metadata(lbbg_gps, lbbg_ref_data_2, ref_cols = c("animal-id", "animal-taxon", "tag-id", "study-name"))
Warning messages:
1: In append_metadata(lbbg_gps, lbbg_ref_data_2, ref_cols = c("animal-id",  :
  The following columns of ref_data will be dropped as they are present in gps as well: `study-name`.
2: Unknown columns: `study-name` 
3: Unknown columns: `study-name`
```

**Comment by damianooldoni** [comment]
Yes, @peterdesmet: you are right. I forgot to remove them from `ref_cols` before performing the join. I took the occasion to further improve unit-testing as well.

**Review by peterdesmet — APPROVED** [review]

**Pull request merged**
