### PR TITLE
Improve GitHub actions

### PR DESCRIPTION
**Pull request by damianooldoni**
After adding a secret to run some actions, e.g. the one described in `pkgdown.yaml` workflow, I worked on this PR to improve the GitHub Action workflows.

1. Test coverage analysis and related badge added via `test-coverage.yaml` workflow
3. `pr-commands.yaml` workflow added (this workflow and the previous one are automatically generated by `usethis::use_tidy_github_actions()`). Thanks to this action we can use /document to run `roxygen2::roxygenise()` and update the PR, and /style to run `styler::style_pkg()` and update the PR.
4. Replace the generic and default` GITHUB_TOKEN` secret name to the real secret name, `GULLTRACKING_TOKEN`, throughout all existent workflows

### CODE REVIEW

**Review by peterdesmet — CHANGES_REQUESTED** [review]
- I would drop the `PULL_REQUEST_TEMPLATE.md`. It is overkill for this project.
- Please revert to the generic `GITHUB_TOKEN`: it is more broadly usable as a variable (note that e.g. pkgdown also retains this variable name).
- Rest looks good, will have to see it in action.

**Comment by damianooldoni** [comment]
Now I understand why I used a personalized secrete name: if I try to set up the secret `GITHUB_TOKEN` I get this error message: 

_Failed to add secret. Name is invalid_

I encountered this problem while setting up secrets for other pkgs like `trias` and `inborutils`. I propose to revert https://github.com/inbo/gulltracking/pull/28/commits/043f1d251b8c37f2c34608d4e986209bd7f201cb and so using `GULLTRACKING_TOKEN`. What do you think?

**Comment by peterdesmet** [comment]
Normally GITHUB_TOKEN is created automatically: https://docs.github.com/en/actions/reference/authentication-in-a-workflow#about-the-github_token-secret

**Comment by damianooldoni** [comment]
ah ok, it's a kind of default secret which we get without even creating it. Really cool! Thanks. 

I also added `/docs` to `.gitignore` as it was commented at the moment. We are going to deploy website via pkgdown.yaml workflow on `gh-pages` now. If you agree, please approve and I will merge. Thank you very much for your clear contributions, always  to-the-point :+1:

**Review by peterdesmet — APPROVED** [review]

**Pull request merged**
